version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "3000:80" # expose port 3000 on host and pass to port 80 of the nginx container
    volumes:
      - "${ros_dir:-.}/containers/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "${ros_dir:-.}/containers/nginx/services.conf:/etc/nginx/conf.d/services/ros.conf"
    depends_on:
      - cognito
      - comm
      - iam
  wait:
    image: waisbrot/wait
    depends_on:
      - db
    environment:
      TARGETS: 'db:5432'
  db:
    image: mdillon/postgis:9.6
    ports:
      - "5432" # - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
  cognito:
    image:
      "${image_repository}/cognito:${rails_env:-development}-${image_tag:-undefined}"
    build:
      context: "${ros_dir:-.}"
      args:
        bundle_string: "${bundle_string:---with=development test}"
        rails_env: "${rails_env:-development}"
        os_packages: "${os_packages:-libpq5 git sudo vim less tcpdump net-tools iputils-ping}"
        project: cognito
        PUID: "${puid:-1000}"
        PGID: "${pgid:-1000}"
    env_file:
      - "${env_dir:-.}/app.env"
      - "${env_dir:-.}/docker-compose.env"
    depends_on:
      - wait
    ports:
      - "3000"
  comm:
    image:
      "${image_repository}/comm:${rails_env:-development}-${image_tag:-undefined}"
    build:
      context: "${ros_dir:-.}"
      args:
        bundle_string: "${bundle_string:---with=development test}"
        rails_env: "${rails_env:-development}"
        os_packages: "${os_packages:-libpq5 git sudo vim less tcpdump net-tools iputils-ping}"
        project: comm
        PUID: "${puid:-1000}"
        PGID: "${pgid:-1000}"
    env_file:
      - "${env_dir:-.}/app.env"
      - "${env_dir:-.}/docker-compose.env"
    depends_on:
      - wait
    ports:
      - "3000"
  iam:
    image:
      "${image_repository}/iam:${rails_env:-development}-${image_tag:-undefined}"
    build:
      context: "${ros_dir:-.}"
      args:
        bundle_string: "${bundle_string:---with=development test}"
        rails_env: "${rails_env:-development}"
        os_packages: "${os_packages:-libpq5 git sudo vim less tcpdump net-tools iputils-ping}"
        project: iam
        PUID: "${puid:-1000}"
        PGID: "${pgid:-1000}"
    env_file:
      - "${env_dir:-.}/app.env"
      - "${env_dir:-.}/docker-compose.env"
    depends_on:
      - wait
    ports:
      - "3000"
    # command: ["tail", "-F", "log/development.log"] # don't start the server
