apiVersion: skaffold/v1beta9
kind: Config
build:
  artifacts:
  - image: railsonservices/cognito
    context: ../..
    docker:
      dockerfile: ../../Dockerfile
      buildArgs:
        project: cognito
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
  local:
    useBuildkit: true
deploy:
  helm:
    releases:
    - name: cognito
      chartPath: ../../devops/helm/charts/service
      values:
        image: railsonservices/cognito
      imageStrategy:
        helm: {}
      wait: false
      overrides:
        nameOverride: cognito
        app:
          envFromSecrets:
            - ros-common
        bootstrap:
          enabled: true
          command: ["bundle","exec","rails","app:ros:db:reset","app:ros:cognito:db:seed"]
        resources:
          limits:
            cpu: 1
            memory: 1.2Gi
          requests:
            cpu: 0.2
            memory: 1Gi
