apiVersion: skaffold/v1beta9
kind: Config
build:
  artifacts:
  - image: railsonservices/iam
    context: ../..
    docker:
      dockerfile: ../../Dockerfile
      buildArgs:
        project: iam
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
  local:
    useBuildkit: true
deploy:
  helm:
    releases:
    - name: iam
      chartPath: ../../devops/helm/charts/service
      values:
        image: railsonservices/iam
      imageStrategy:
        helm: {}
      wait: false
      setValues:
        nameOverride: iam
        bootstrap.enabled: true
        bootstrap.command: '{"bundle","exec","rails","app:ros:db:reset","app:ros:iam:db:seed"}'
        resources.limits.cpu: 1
        resources.limits.memory: 2Gi
        resources.requests.cpu: 0.5
        resources.requests.memory: 1.5Gi
