# Configuration values defined here will be overridden by any values defined in environments/[ROS_ENV].yml
---
# Developer discovers the project and runs 'gem install ros'
# ros new trading        # creates ./trading/config ./trading/services ./trading/devops, etc
# cd trading
# ros devops:provision   # creates the infra defined in devops dir
# ros g service billing  # generates a new service (rails app), updates relevant config files, etc
# ros devops:deploy      # deploys the platform

# new project seems to need:
# devops/terraform/aws/deployments/instance/variables.tf values for:
# route53_zone_main_name, route53_zone_this_name, etc
# TODO: These variables should not have defaults. They should be written by ros gem to a tfvars file
# TODO: Determine where is the standard location for tfvars; same dir regardless of inrastructure type

# new service seems to need:
# helm/charts/[service]
# terraform/aws/modules/kubernetes/templates/helm-values/[service].tpl (could this be moved to a cloud agnotic path?)
# terraform/aws/modules/kubernetes/variables.tf adds vars here for the docker version to deploy

# TODO: move contents of README to guides and have README point to the guides
# TODO: terraform/aws/deployments/instance/modules/server/main.tf has a name_prefix set to 'ros'. Why?/server/main.tf has a name_prefix set to 'ros'. Why?

compose:
  project_name: ros
  image_repository: rails-on-services

# Defines the services that will be running on the platform and their default values
services:
  monitoring: # prom + grafana
    enabled: false
  logging: # fluentd
    enabled: false
    type: localstack # :s3
  iam:
    this: that
  cognito:
    this: that
  comm:
    this: that
  storage:
    # requires localstack running s3 or and S3 bucket, SFTP container, Rails Storage service
    # if enabled then either the ALB or the SG needs to permit the SFTP port
    # If localstack include that in COMPIOSE_FILE in .env
    # If S3 then when calling ros infra:provision it writes a value to tfvars that has TF create the S3 bucket
    enabled: true
    type: localstack # :s3
    mount: yes
  billing:
    enabled: false
  survey:
  reward:
  game:
  loyalty:
