version: '3'
# TODO: Add prometheus and Grafana
services:
  wait:
    depends_on:
      - fluentd
    environment:
      # TARGETS: 'db:5432,rabbitmq:5672,elasticsearch:9200,redis:6379,fluentd:24224,localstack:4572'
      # TARGETS: 'db:5432,rabbitmq:5672,redis:6379'

  fluentd:
    image: fluent/fluentd:v1.3.2-debian
    ports:
      - '24224:24224'
      - '24224:24224/udp'
    volumes:
      - './fluentd/log:/fluentd/log'
      - './fluentd:/fluentd/etc'
    environment:
      FLUENTD_CONF: rails.conf

  prometheus:
    image: prom/prometheus
    # restart: on-failure
    ports:
      - '9090:9090'
    volumes:
      - "${HOME}/${COMPOSE_PROJECT_NAME}/prometheus/data:/prometheus"
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana
    # restart: on-failure
    ports:
      - '4000:3000'
    volumes:
      - "${HOME}/${COMPOSE_PROJECT_NAME}/grafana/data:/var/lib/grafana"
      - "./grafana/provisioning:/etc/grafana/provisioning"
      - "./grafana/dashboards:/etc/grafana/dashboards"
    user: "${GRAFANA_ID}"

