version: '3'
services:
  cognito:
    image:
      "${IMAGE_REPOSITORY}/cognito:${RAILS_ENV:-development}-${IMAGE_TAG:-latest}"
    build:
      # .. works when building in the project/ros dir
      # ../ros works when building in the project dir
      context: "${CONTEXT_DIR:-..}"
      args:
        bundle_string: "${BUNDLE_STRING:---with=development test}"
        rails_env: "${RAILS_ENV:-development}"
        os_packages: "${OS_PACKAGES:-libpq5 git sudo vim less tcpdump net-tools iputils-ping}"
        project: cognito
        PUID: "${PUID:-1000}"
        PGID: "${PGID:-1000}"
    env_file:
      - ../config/env
      - ./env
    depends_on:
      - wait
    ports:
      - "3000"

  comm:
    image:
      "${IMAGE_REPOSITORY}/comm:${RAILS_ENV:-development}-${IMAGE_TAG:-latest}"
    build:
      context: "${CONTEXT_DIR:-..}"
      args:
        bundle_string: "${BUNDLE_STRING:---with=development test}"
        rails_env: "${RAILS_ENV:-development}"
        os_packages: "${OS_PACKAGES:-libpq5 git sudo vim less tcpdump net-tools iputils-ping}"
        project: comm
        PUID: "${PUID:-1000}"
        PGID: "${PGID:-1000}"
    env_file:
      - ../config/env
      - ./env
    depends_on:
      - wait
    ports:
      - "3000"

  iam:
    image:
      "${IMAGE_REPOSITORY}/iam:${RAILS_ENV:-development}-${IMAGE_TAG:-latest}"
    build:
      context: "${CONTEXT_DIR:-..}"
      args:
        bundle_string: "${BUNDLE_STRING:---with=development test}"
        rails_env: "${RAILS_ENV:-development}"
        os_packages: "${OS_PACKAGES:-libpq5 git sudo vim less tcpdump net-tools iputils-ping}"
        project: iam
        PUID: "${PUID:-1000}"
        PGID: "${PGID:-1000}"
    env_file:
      - ../config/env
      - ./env
    depends_on:
      - wait
    ports:
      - "3000"
    # command: ["tail", "-F", "log/development.log"] # don't start the server
