apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cognito.fullname" . }}
  labels:
    app: {{ include "cognito.name" . }}
    app.kubernetes.io/name: {{ include "cognito.name" . }}
    helm.sh/chart: {{ include "cognito.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "cognito.name" . }}
      app.kubernetes.io/name: {{ include "cognito.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "cognito.name" . }}
        app.kubernetes.io/name: {{ include "cognito.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | trim | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbePath | quote }}
              port: http
          {{- with .Values.app.command }}
          command: 
            {{- toYaml . | trim | nindent 12 }}
          {{- end }}
          {{- with .Values.app.env }}
          env:
            {{- range $name, $value := . }}
            - name: {{ $name | quote }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          {{- if or (.Values.app.envFromSecrets) (.Values.app.envFromConfigMaps) }}
          envFrom:
            {{- range .Values.app.envFromConfigMaps }}
            - configMapRef:
                name: {{ . | quote }}
            {{- end }}
            {{- range .Values.app.envFromSecrets }}
            - secretRef:
                name: {{ . | quote }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
