kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "fluentd-tcp.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "fluentd-tcp.name" . }}
    helm.sh/chart: {{ include "fluentd-tcp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  input.conf: |
    <source>
      @type forward
      port {{ .Values.containerPort }}
    </source>
{{- range $key, $value := .Values.configMaps }}
  {{ $key }}: |-
{{ $value | indent 4 }}
{{- end }}
